name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the Python version

      - name: Install dependencies
        run: pipenv install --deploy --ignore-pipfile

      - name: Run tests
        run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd starter/backend
          docker build -t mp-backend:${{ github.sha }} .

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Optional

      - name: Push Docker image to ECR
        run: |
          docker tag mp-backend:${{ github.sha }} <your-ecr-repo>:${{ github.sha }}
          docker push <your-ecr-repo>:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=<your-ecr-repo>:${{ github.sha }}
          kustomize build | kubectl apply -f -

