name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FRONTEND_PATH: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify the Node.js version

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: CI=true npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      REACT_APP_MOVIE_API_URL: ${{ secrets.REACT_APP_MOVIE_API_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} -t mp-frontend:${{ github.sha }} ${{ env.FRONTEND_PATH }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Optional

      - name: Tag and Push Docker Image
        run: |
          docker tag mp-frontend:${{ github.sha }} <your-ecr-repo>:${{ github.sha }}
          docker push <your-ecr-repo-url>:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=<your-ecr-repo>:${{ github.sha }}
          kustomize build | kubectl apply -f -
