name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./setup/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Export Terraform outputs
        id: outputs
        run: terraform output -json > terraform_outputs.json

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set environment variables from Terraform outputs
        id: set-vars
        run: |
          echo "BACKEND_ECR=$(jq -r '.backend_ecr.value' terraform_outputs.json)" >> $GITHUB_ENV

  lint:
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run lint
        run: pipenv run lint
        
  test:
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    env:
      FRONTEND_PATH: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run test
        run: pipenv run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [terraform, lint, test]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd starter/backend
          docker build -t mp-backend:${{ github.sha }} .

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push Docker image to ECR
        run: |
          docker tag mp-backend:${{ github.sha }} ${{ env.BACKEND_ECR }}:${{ github.sha }}
          docker push ${{ env.BACKEND_ECR }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=${{ env.BACKEND_ECR }}:${{ github.sha }}
          kustomize build | kubectl apply -f -

  terraform-destroy:
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./setup/terraform
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve